version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      REACT_APP_API_URL: http://localhost:3000/api
volumes:
  db_data: